// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc-BR0T0FUJqUIntAWrK46RkSNHWTMpLI',
    appId: '1:406913672145:web:094fd72d2c7fed0b5fb6f0',
    messagingSenderId: '406913672145',
    projectId: 'workoutapp2025',
    authDomain: 'workoutapp2025.firebaseapp.com',
    storageBucket: 'workoutapp2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAAkMyu_F3msSITcNPvJRgiundjggOZOY',
    appId: '1:406913672145:android:340f1db32696a0c35fb6f0',
    messagingSenderId: '406913672145',
    projectId: 'workoutapp2025',
    storageBucket: 'workoutapp2025.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc-BR0T0FUJqUIntAWrK46RkSNHWTMpLI',
    appId: '1:406913672145:web:c53ef9279fd0040e5fb6f0',
    messagingSenderId: '406913672145',
    projectId: 'workoutapp2025',
    authDomain: 'workoutapp2025.firebaseapp.com',
    storageBucket: 'workoutapp2025.firebasestorage.app',
  );
}
